import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Varsha",
      email: "vashuka@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "vashuka",
      email: "vashuka1@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: " sunar top",
      category: "top",
      image: "/images/1t.jpg",
      price: 120,
      countInStock: 1,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "semos top",
      category: "top",
      image: "/images/2t.jpg",
      price: 320,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 20,
      description: "high quality product",
    },
    {
      name: " top",
      category: "top",
      image: "/images/3t.jpg",
      price: 190,
      countInStock: 11,
      brand: "Nike",
      rating: 2.5,
      numReviews: 11,
      description: "high quality product",
    },
    {
      name: " vaishnavi top",
      category: "top",
      image: "/images/4t.jpg",
      price: 420,
      countInStock: 2,
      brand: "Nike",
      rating: 4.0,
      numReviews: 13,
      description: "high quality product",
    },
    {
      name: " sunar jeans",
      category: "top",
      image: "/images/5t.jpg",
      price: 220,
      countInStock: 0,
      brand: "Nike",
      rating: 1.5,
      numReviews: 9,
      description: "high quality product",
    },
    {
      name: " siso jeans",
      category: "top",
      image: "/images/6t.jpeg",
      price: 400,
      countInStock: 4,
      brand: "adidas",
      rating: 3.0,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
